# Generated by Django 4.0.5 on 2022-08-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
