# Generated by Django 4.0.5 on 2022-08-10 01:58

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
